export { default as FormSignIn } from './FormLogin/FormSignIn'
export { default as FormSignUp } from './FormLogin/FormSignUp'
export { default as CanvasLogo } from './CanvasLogo/CanvasLogo'
export { default as MagneticButton } from './MagneticButton/MagneticButton'
export { default as ModalLogin } from './ModalLogin/ModalLogin'