export { default as FormSignIn } from './Login/FormLogin/FormSignIn'
export { default as FormSignUp } from './Login/FormLogin/FormSignUp'
export { default as CanvasLogo } from './Login/CanvasLogo/CanvasLogo'
export { default as MagneticButton } from './Login/MagneticButton/MagneticButton'
export { default as ModalLogin } from './Login/ModalLogin/ModalLogin'
export { default as SvgLogin } from './Login/SvgLogin/SvgLogin'
